#!/bin/tcsh -f 

set dat=hippie_string0.5_interactome_gn_path_goproc_plm_entave_fea.txt
set pafea=hippie_string0.5_interactome_gn_path_fea.txt
set gofea=hippie_string0.5_interactome_gn_goproc_fea.txt
set dat0=$dat:r:t
set pafea0=$pafea:r:t
set gofea0=$gofea:r:t

# get feature for  pathways
if ( ! -e $pafea && -e $dat  ) then
awk '{c=$1;for(l=1;l<=2364;l++) c=c " " $(l+1);print c,"#",$NF}' <$dat >! $pafea 
endif 
# get feature for  Go process 
if ( ! -e $gofea && -e $dat ) then
awk '{c=$1;for(l=1;l<=12536;l++) c=c " " $(l+1+2364);print c,"#",$NF}' <$dat >! $gofea 
endif 

if ( ! -e $pafea0"_zv.txt" ) then
./scan_u_z.job $pafea 
endif

cat CTD_pathways.txt  $pafea0"_zv.txt" | awk '{i=i+1;if(i<=2363){t[i]=$0}else{j=j+1;if(j==1) print $2,"number of pathways";if(j>1) print $2,t[$1-2]}}' | sort -gr -k1  >! path_zv_name.txt

if ( ! -e  $gofea0"_zv.txt" ) then
./scan_u_z.job $gofea 
endif

cat human_go.obo_bioprocess   $gofea0"_zv.txt" | awk '{i=i+1;if(i<=12535){t[i]=$0}else{j=j+1;if(j==1) print $2,"number of GO processes";if(j>1) print $2,t[$1-2]}}' |sort -gr -k1  >! goproc_zv_name.txt

